### ISSUE TITLE
Demonstration of batch correction using scRNA-seq datasets

### ISSUE THREAD

**Issue by XiHuYan** [andy1764/PARE#1]
I'm confused about what the vignette is trying to demonstrate. Could you provide a detailed tutorial showing how to apply PARE for batch correction on single-cell datasets?

Thanks.

**Comment by andy1764** [comment]
Thanks for this request and apologies for the delay. Just reach out to chenandr@musc.edu and I'm happy to send over code for the single-cell application from the paper
